const CREATE_PRODUCT_REPOSITORY_TOKEN = Symbol('CreateProductRepository')

const DELETE_PRODUCT_REPOSITORY_TOKEN = Symbol('DeleteProductRepository')

const FIND_PRODUCT_BY_ID_REPOSITORY_TOKEN = Symbol('FindProductByIdRepository')

const UPDATE_PRODUCT_REPOSITORY_TOKEN = Symbol('UpdateProductRepository')

const SEARCH_PRODUCTS_REPOSITORY_TOKEN = Symbol('SearchProductsRepository')

const BEST_SELLERS_PRODUCTS_REPOSITORY_TOKEN = Symbol(
  'BestSellersProductRepository',
)

export {
  CREATE_PRODUCT_REPOSITORY_TOKEN,
  DELETE_PRODUCT_REPOSITORY_TOKEN,
  FIND_PRODUCT_BY_ID_REPOSITORY_TOKEN,
  UPDATE_PRODUCT_REPOSITORY_TOKEN,
  SEARCH_PRODUCTS_REPOSITORY_TOKEN,
  BEST_SELLERS_PRODUCTS_REPOSITORY_TOKEN,
}
