const SEARCH_ALL_ORDERS_FOR_ADMIN_REPOSITORY_TOKEN = Symbol(
  'SearchOrdersForAdminRepository',
)

const FIND_ORDER_BY_ID_REPOSITORY_TOKEN = Symbol('FindOrderByIdRepository')

const SEARCH_ORDERS_BY_USER_FOR_ADMIN_REPOSITORY_TOKEN = Symbol(
  'FindOrdersByUserForAdminRepository',
)

const SEARCH_ORDERS_FOR_USER_REPOSITORY_TOKEN = Symbol(
  'SearchOrdersForUserRepository',
)

const NEXT_STATUS_ORDER_REPOSITORY_TOKEN = Symbol(
  'NextStatusOrderRepositoryToken',
)

export {
  SEARCH_ALL_ORDERS_FOR_ADMIN_REPOSITORY_TOKEN,
  FIND_ORDER_BY_ID_REPOSITORY_TOKEN,
  SEARCH_ORDERS_FOR_USER_REPOSITORY_TOKEN,
  SEARCH_ORDERS_BY_USER_FOR_ADMIN_REPOSITORY_TOKEN,
  NEXT_STATUS_ORDER_REPOSITORY_TOKEN,
}
