const ADD_TO_WISHLIST_REPOSITORY_TOKEN = Symbol('AddToWishlistRepository')

const REMOVE_FROM_WISHLIST_REPOSITORY_TOKEN = Symbol(
  'RemoveFromWishlistRepository',
)

const CLEAR_WISHLIST_REPOSITORY_TOKEN = Symbol('ClearWishlistRepository')

const SEARCH_WISHLISTS_REPOSITORY_TOKEN = Symbol('SearchWishlistsRepository')

export {
  ADD_TO_WISHLIST_REPOSITORY_TOKEN,
  REMOVE_FROM_WISHLIST_REPOSITORY_TOKEN,
  CLEAR_WISHLIST_REPOSITORY_TOKEN,
  SEARCH_WISHLISTS_REPOSITORY_TOKEN,
}
