const CREATE_CATEGORY_REPOSITORY_TOKEN = Symbol('CreateCategoryRepository')

const DELETE_CATEGORY_REPOSITORY_TOKEN = Symbol('DeleteCategoryRepository')

const FIND_CATEGORY_BY_ID_REPOSITORY_TOKEN = Symbol(
  'FindCategoryByIdRepository',
)

const UPDATE_CATEGORY_REPOSITORY_TOKEN = Symbol('UpdateCategoryRepository')

const SEARCH_CATEGORIES_REPOSITORY_TOKEN = Symbol('SearchCategoriesRepository')

export {
  CREATE_CATEGORY_REPOSITORY_TOKEN,
  DELETE_CATEGORY_REPOSITORY_TOKEN,
  FIND_CATEGORY_BY_ID_REPOSITORY_TOKEN,
  UPDATE_CATEGORY_REPOSITORY_TOKEN,
  SEARCH_CATEGORIES_REPOSITORY_TOKEN,
}
