import '@modules/account/container/index'
import '@modules/category/container/index'
import '@modules/user/container/index'
import '@modules/files/container/index'
import '@modules/products/container/index'
